name: finalx
description: Some random frontend app for some random esp32 project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
